//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Burrito_T
    {
        public int id { get; set; }
        public string IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Precio { get; set; }
        public string comenatrio { get; set; }
        public string Ticket { get; set; }
        public string Idnombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Idtelefono { get; set; }
        public string Estado { get; set; }
    }
}
