//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FacturacionEntities : DbContext
    {
        public FacturacionEntities()
            : base("name=FacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Factura_Burrito> Factura_Burrito { get; set; }
        public virtual DbSet<Factura_Burrito_T> Factura_Burrito_T { get; set; }
        public virtual DbSet<Factura_Chimi> Factura_Chimi { get; set; }
        public virtual DbSet<Factura_Chimi_T> Factura_Chimi_T { get; set; }
        public virtual DbSet<Invetario> Invetario { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<NombreCliente> NombreCliente { get; set; }
        public virtual DbSet<ProductoChimi> ProductoChimi { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
    
        public virtual ObjectResult<string> SP_Generar_Turno(string servicio )
        {
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Generar_Turno", servicioParameter);
        }
    }
}
