//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminBSB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gastos_Diario
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Favor Completar el Campo de {0}")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "Favor Colocar el {0}")]
        public Nullable<int> Precio { get; set; }
        [Required(ErrorMessage = "Favor Colocar la  {0}")]
        public Nullable<System.DateTime> Fecha { get; set; }
        [Required(ErrorMessage = "Favor Completar  Campo  {0}")]
        public string Nombre { get; set; }
    }
}
