//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminBSB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gastos
    {
        public int id { get; set; }
        [Required(ErrorMessage = "El campo \"{0}\" es requerido.")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El campo \"{0}\" es requerido.")]
        public Nullable<int> Precio { get; set; }
        [Required(ErrorMessage = "El campo \"{0}\" es requerido.")]
        public Nullable<System.DateTime> Fecha { get; set; }
        [Required(ErrorMessage = "El campo \"{0}\" es requerido.")]
        public string Nombre { get; set; }

    }
}
