//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminBSB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FacturacionEntities : DbContext
    {
        public FacturacionEntities()
            : base("name=FacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Detalle_Factura_T> Detalle_Factura_T { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<Gastos_Diario> Gastos_Diario { get; set; }
        public virtual DbSet<Invetario> Invetario { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
    
        public virtual ObjectResult<string> SP_Generar_Turno(string servicio)
        {
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Generar_Turno", servicioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Cuadre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Cuadre");
        }
    
        public virtual int SP_LimpiarTabla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LimpiarTabla");
        }
    }
}
